site_name: CvHub Docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js

theme:
  name: material

nav:
  - Home: index.md

  - Architecture:
      - Overview: architecture/overview.md

  - Dev Notes:
      - gRPC:
          - Overview: dev-notes/gRPC/gRPC.md
          - Proto: dev-notes/gRPC/gRPC_proto.md
          - Patterns: dev-notes/gRPC/gRPC_patterns.md
          - Service Impl: dev-notes/gRPC/gRPC_service_impl.md
          - Interceptor: dev-notes/gRPC/gRPC_Interceptor.md

      - LLM:
          - Model Basics: dev-notes/llm/01_llm_model_basics.md
          - Precision and Quantization: dev-notes/llm/02_llm_precision_and_quantization.md
          - Model Format: dev-notes/llm/03_llm_model_formats.md
          - Inference Engine: dev-notes/llm/04_llm_inference_engines.md
          - Serving: dev-notes/llm/05_llm_serving.md
          - Application: dev-notes/llm/06_llm_applications.md

      - RAG System:
          - Overview: dev-notes/rag/01_rag_overview.md
          - Document Ingestion & Chunking: dev-notes/rag/02_document_ingestion_and_chunking.md
          - Embedding & Indexing: dev-notes/rag/03_embedding_and_indexing.md
          - Retrieval Pipeline: dev-notes/rag/04_retrieval_pipeline.md
          - Context Generation & Grounding: dev-notes/rag/05_context_generation_and_grounding.md
          - Evaluation, Operations & Security: dev-notes/rag/06_rag_evaluation_operations_security.md