site_name: CvHub Docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme: 
  name: material

nav:
  - Home: index.md
  - Dev Notes:
    - gRPC:
      - Overview: dev-notes/gRPC/gRPC.md
      - Proto: dev-notes/gRPC/gRPC_proto.md
      - Patterns: dev-notes/gRPC/gRPC_patterns.md
      - Service Impl: dev-notes/gRPC/gRPC_service_impl.md
      - Interceptor: dev-notes/gRPC/gRPC_Interceptor.md